CREATE TABLE IF NOT EXISTS "User" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  passwordHash TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  failedLoginAttempts INTEGER NOT NULL DEFAULT 0,
  lockedUntil DATETIME
);

CREATE TABLE IF NOT EXISTS "Session" (
  token TEXT PRIMARY KEY,
  userId INTEGER NOT NULL,
  expiresAt DATETIME NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
